services:
  # Full-Stack Web Service (Backend API + Static Frontend)
  - type: web
    name: evolvo-uz
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: evolvo-postgres
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TELEGRAM_ADMIN_CHANNEL_ID
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    autoDeploy: true
    
databases:
  # PostgreSQL Database
  - name: evolvo-postgres
    databaseName: evolvo
    user: evolvo_user
    plan: starter